FROM python:3.9

WORKDIR /app
COPY requirements.txt requirements.txt

ENV LD_LIBRARY_PATH="/usr/local/nvidia/lib64"

RUN pip --default-timeout=1000 install parlai
RUN pip --default-timeout=1000 install -r requirements.txt

# RUN pip --mount=type=cache,target=/root/.cache --default-timeout=1000 install parlai
# RUN pip --mount=type=cache,target=/root/.cache --default-timeout=1000 install -r requirements.txt

COPY . .

RUN python3 -u src/initModel.py

CMD [ "python3", "-u", "src/server.py"]
